### ISSUE TITLE
Launch Fail

### ISSUE THREAD

**Issue by keremlov** [FTBTeam/FTB-Unstable-1.14#7]
https://paste.feed-the-beast.com/view/82d79543 

Crashes at launch

**Comment by drizzs** [comment]
Lol funny you posted in that other issue so i'd get a notice about it. Not very nice. This issue looks like your problem. Your launch fails because either your minecraft install is not ok or your java is not ok, could also be twitch if you use that. I'd reinstall all these things 1 by 1 to see which is doing it. But its not the modpack, as you can see you dont even get that far. idk if you can reinstall forge of if it just comes on an already pre-set version. 

Failed to find Minecraft resource version 1.14.4-20190719.225934 at C:\Users\oktay\Documents\Curse\Minecraft\Install\libraries\net\minecraftforge\forge\1.14.4-28.0.46\forge-1.14.4-28.0.46-client.jar

**Comment by drizzs** [comment]
"I was eventually able to fix the problem by manually downloading and installing forge into the default Minecraft installation and copying the needed libraries over to the Twitch installation."

Did you even try this? the other guy in the other open issue said he did this?????????????

**Comment by keremlov** [comment]
I reinstalled minecraft , java and the modpack again but didn't seem to work. And I dont know how to do what the other guy said. Should I just copy the mods file into the forged minecraft ?

**Comment by keremlov** [comment]
Okay  I have tried to download forge and installing it and then copying the library folder to minecraft/install folder in curse folder. And redownloading the pack. But it didnt work either.

**Comment by drizzs** [comment]
Sorry but this issue isnt with the pack or a mod i work on, so i cant help you, all i can tell you is that the issue is with the stuff you got going on. You'll have to ask around or wait till someone else responds! <3 patience is a virtue.

**Comment by keremlov** [comment]
Welll I just coppied all the files to the other custom profile that I made and  I managed to open it. I Don't know what's up with that lmao

**Comment by keremlov** [comment]
OH Good news is I manage to make it so that it opens however bad news is that it crashes while trying to load mods https://paste.feed-the-beast.com/view/e01ed322 Maybe it's not about me anymore ?

**Comment by keremlov** [comment]
https://paste.feed-the-beast.com/view/aaba44f6

**Comment by keremlov** [comment]
I deleted curse folder and reinstalled twitch app and it worked! thanks you for helping
